name: Update Homebrew formula

on:
  push:
   tags:
     - '*'

permissions: write-all

jobs:
  update-homebrew-formula:
    runs-on: ubuntu-latest
    env:
      Version: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "src"
          ref: "main"
          persist-credentials: false

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "dest"
          ref: "main"
          repository: "kevinm6/homebrew-battery-cli"
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions [Bot]"
          git config --global user.email "${{ secrets.BOT_EMAIL }}"

      - name: Get shasum
        id: shasum
        run: |
          echo "shasum=$(curl -sL "https://github.com/kevinm6/battery-cli/archive/refs/tags/${{ env.Version }}.tar.gz" | shasum -a 256 | awk '{printf $1}')" >> $GITHUB_ENV

      - name: Update formula
        shell: bash
        working-directory: dest
        run: |
          echo '
            class BatteryCli < Formula
              desc "CLI for managing the battery charging status"

              homepage "https://github.com/kevinm6/battery-cli"
              url "https://github.com/kevinm6/battery-cli/archive/refs/tags/${{ env.Version }}.tar.gz"
              sha256 "${{ env.shasum }}"
              # version "${{steps.version}}"
              license "MIT"

              head "https://github.com/kevinm6/battery-cli.git", branch: "main"

              conflicts_with cask: "battery", because: "both install binaries that can interfere"

              on_macos do
                on_arm do
                  url "https://github.com/kevinm6/battery-cli/archive/refs/tags/${{ env.Version }}.tar.gz"
                  sha256 "${{ env.shasum }}"

                  def install
                    bin.install "dist/smc"
                    bin.install "battery-cli" => "battery"
                  end
                end
              end

              test do
                system "false"
              end
            end' > battery-cli.rb

          git add battery-cli.rb

          git commit -m "GH-Action: Update formula [$(date)]"

          git push origin main


